[package]
name = "vpm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.26"
clap = { version = "4.1.8", features = ["derive"] }
crossterm = "0.27.0"
ratatui = { version = "0.22.0", features = ["all-widgets"] }
# sqlx = { version = "0.6.2", features = ["sqlite", "chrono", "runtime-tokio-rustls"] }
# tokio = { version = "1.25.0", features = ["full"] }
